// Subscription plan pricing/feature data — the single source of truth for
// what SubscribePage and LandingPage display, and what create-payment
// (supabase/functions/create-payment/index.ts, PLANS map) charges for.
// Keep price values in sync with that edge function.
export const PLANS = [
  {
    id: "starter",
    name_ar: "Starter",
    name_en: "Starter",
    price: 495,
    cycle_ar: "سنوياً",
    cycle_en: "/year",
    description_ar: "للمالكين الجدد ولأصحاب القطعان الصغيرة.",
    description_en: "For new owners and small herds.",
    features_ar: [
      "حتى 5 أصول",
      "اسطبل واحد",
      "تنبيهات السياج الجغرافي",
      "تقارير صحية شهرية",
      "دعم عبر الواتساب",
    ],
    features_en: [
      "Up to 5 assets",
      "1 stable",
      "Geofence alerts",
      "Monthly health reports",
      "WhatsApp support",
    ],
    accent: "#006c35",
    badge: null,
  },
  {
    id: "pro",
    name_ar: "Pro",
    name_en: "Pro",
    price: 695,
    cycle_ar: "سنوياً",
    cycle_en: "/year",
    description_ar: "للمزارع المتوسطة وأصحاب الخيول.",
    description_en: "For mid-size farms and horse owners.",
    features_ar: [
      "حتى 20 أصلاً",
      "5 اسطبلات",
      "تتبع نبض القلب الحي",
      "تقارير أسبوعية + تصدير PDF",
      "دعم أولوية 24/7",
    ],
    features_en: [
      "Up to 20 assets",
      "5 stables",
      "Live heart-rate tracking",
      "Weekly reports + PDF export",
      "24/7 priority support",
    ],
    accent: "#006c35",
    badge: "ar:الأكثر شيوعاً|en:Most popular",
  },
  {
    id: "enterprise",
    name_ar: "Enterprise",
    name_en: "Enterprise",
    price: 995,
    cycle_ar: "سنوياً",
    cycle_en: "/year",
    description_ar: "للمؤسسات الكبيرة ومربي الصقور.",
    description_en: "For large estates and falcon breeders.",
    features_ar: [
      "أصول غير محدودة",
      "اسطبلات غير محدودة",
      "خرائط تضاريس 3D",
      "API مخصص + Webhooks",
      "مدير حساب مخصص",
    ],
    features_en: [
      "Unlimited assets",
      "Unlimited stables",
      "3D terrain maps",
      "Custom API + Webhooks",
      "Dedicated account manager",
    ],
    accent: "#c5a55a",
    badge: null,
  },
];
